### ISSUE TITLE
forum mesaj formundan kasıt nedir tam olarak açıklarmısın tam anlayamadım ?

### ISSUE THREAD

**Issue by halilbarim** [100ProjedeSeniorWebDeveloper/2-hmtl4#2]

**Comment by kevsersrca** [comment]
Blog yazısı formundan daha az karakter alan bir form tasarlıycaksın . Text kısmı daha küçük karakteri sınırlı olacak

**Comment by kemalkanok** [comment]
@kevsersrca eğer konu bittiyse ki bu bitmiş gibi görünüyor kütfen issueyu kapat
